# Labels.
"type:feature": ['feature/*', 'feat/*']
"type:bug": ['bug/*', 'bugfix/*', 'fix/*']
"type:hotfix": ['hotfix/*', 'hot/*', 'urgent/*']
"type:docs": ['docs/*', 'doc/*']
"type:enhancement": ['enhancement/*', 'enhance/*', 'chore/*', 'improve/*', 'improvement/*']
"type:maintenance": ['maintenance/*', 'robot/*', 'devops/*', 'update/*']
"type:dependency": ['renovate/*', 'deps/*']
"type:security": ['sec/*', 'security/*']
"type:ignore": ['ignore/*']
"type:tests": ['test/*', 'tests/*', 'coverage/*']
