package io.github.felipebonezi.cipherizy.test.algorithm.aes;

import static org.junit.Assert.assertEquals;

import io.github.felipebonezi.cipherizy.CipherException;
import io.github.felipebonezi.cipherizy.ICipher;
import io.github.felipebonezi.cipherizy.algorithm.CipherFactory;
import java.nio.charset.StandardCharsets;
import org.junit.Assert;
import org.junit.Test;

/**
 * Cipher class test.
 */
public class AESCipherLargeTextTest {
  
  // region Large text.
  private static final String LARGE_TEXT =
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Commodo quis imperdiet massa tincidunt nunc pulvinar sapien et ligula. Iaculis eu non diam phasellus vestibulum lorem sed risus ultricies. Vitae aliquet nec ullamcorper sit amet risus nullam eget. Vulputate eu scelerisque felis imperdiet proin fermentum leo vel. Sed cras ornare arcu dui vivamus arcu felis bibendum. Nulla facilisi morbi tempus iaculis urna id. Lobortis elementum nibh tellus molestie nunc non blandit. Eu mi bibendum neque egestas. A condimentum vitae sapien pellentesque habitant.\n" +
          "\n" +
          "Posuere ac ut consequat semper viverra. Massa vitae tortor condimentum lacinia quis vel. Suspendisse sed nisi lacus sed viverra tellus in. Velit dignissim sodales ut eu sem integer vitae justo eget. Suspendisse faucibus interdum posuere lorem ipsum dolor sit amet consectetur. Integer malesuada nunc vel risus commodo viverra maecenas accumsan. Sit amet volutpat consequat mauris nunc congue nisi vitae. Dignissim suspendisse in est ante in nibh. Magna fermentum iaculis eu non diam phasellus vestibulum lorem sed. Vestibulum rhoncus est pellentesque elit ullamcorper. Egestas diam in arcu cursus euismod quis viverra nibh cras. Purus faucibus ornare suspendisse sed nisi lacus sed. Dui faucibus in ornare quam viverra. Laoreet id donec ultrices tincidunt arcu non sodales neque sodales. Et malesuada fames ac turpis.\n" +
          "\n" +
          "Lacinia at quis risus sed vulputate odio ut. Purus viverra accumsan in nisl nisi scelerisque eu ultrices vitae. In pellentesque massa placerat duis. Magna fermentum iaculis eu non diam phasellus. Ultrices dui sapien eget mi proin sed libero enim. Pellentesque id nibh tortor id aliquet lectus proin nibh nisl. Mattis aliquam faucibus purus in massa tempor. Amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus. Pellentesque massa placerat duis ultricies lacus sed turpis. Sagittis vitae et leo duis ut diam quam nulla porttitor. Quam pellentesque nec nam aliquam sem et tortor consequat id. Felis bibendum ut tristique et egestas. Bibendum est ultricies integer quis auctor. Magna fringilla urna porttitor rhoncus dolor purus non enim. Molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit sed. Dolor sit amet consectetur adipiscing. Urna cursus eget nunc scelerisque. Non curabitur gravida arcu ac tortor dignissim convallis aenean et.\n" +
          "\n" +
          "Mauris vitae ultricies leo integer malesuada nunc vel risus commodo. Nibh cras pulvinar mattis nunc sed. Arcu non sodales neque sodales. Amet mauris commodo quis imperdiet. Eget velit aliquet sagittis id consectetur purus ut faucibus pulvinar. Justo laoreet sit amet cursus sit amet dictum sit. Senectus et netus et malesuada fames ac. Netus et malesuada fames ac turpis egestas integer eget aliquet. Condimentum lacinia quis vel eros donec ac odio. Condimentum lacinia quis vel eros donec ac odio tempor. Pellentesque adipiscing commodo elit at imperdiet dui accumsan sit amet. Posuere morbi leo urna molestie at elementum. Risus feugiat in ante metus dictum at tempor.\n" +
          "\n" +
          "Amet cursus sit amet dictum sit amet justo. Venenatis a condimentum vitae sapien. Tempus iaculis urna id volutpat lacus. Risus nullam eget felis eget nunc lobortis mattis. Elit sed vulputate mi sit amet mauris commodo quis. Nulla pharetra diam sit amet nisl suscipit. Aliquam etiam erat velit scelerisque in dictum non consectetur. Nibh tortor id aliquet lectus proin nibh nisl. Quis blandit turpis cursus in hac habitasse. Ac tortor dignissim convallis aenean et. Ornare quam viverra orci sagittis eu volutpat.\n" +
          "\n" +
          "Donec ultrices tincidunt arcu non sodales neque sodales. Commodo elit at imperdiet dui. Ante metus dictum at tempor. Feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper. Mauris ultrices eros in cursus turpis. Ipsum a arcu cursus vitae congue mauris. Sit amet nisl suscipit adipiscing bibendum est. Volutpat diam ut venenatis tellus. Dolor sit amet consectetur adipiscing elit pellentesque habitant. Egestas congue quisque egestas diam in arcu cursus euismod. Libero nunc consequat interdum varius sit amet. Leo vel orci porta non pulvinar neque. Nibh praesent tristique magna sit amet. Fusce id velit ut tortor pretium. Semper risus in hendrerit gravida rutrum. Elementum eu facilisis sed odio morbi quis. Urna molestie at elementum eu facilisis sed. Pulvinar proin gravida hendrerit lectus a. Nibh mauris cursus mattis molestie a iaculis.\n" +
          "\n" +
          "Ut enim blandit volutpat maecenas volutpat blandit aliquam etiam. Amet dictum sit amet justo donec enim diam vulputate ut. Ultrices neque ornare aenean euismod elementum nisi quis eleifend. Mi proin sed libero enim sed faucibus turpis in. Egestas purus viverra accumsan in. Maecenas pharetra convallis posuere morbi leo. Condimentum vitae sapien pellentesque habitant morbi tristique senectus. Ac auctor augue mauris augue neque gravida in fermentum et. Eget est lorem ipsum dolor sit amet. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Vitae purus faucibus ornare suspendisse sed nisi lacus sed viverra. Aenean vel elit scelerisque mauris pellentesque. In ornare quam viverra orci sagittis eu volutpat odio facilisis. Non curabitur gravida arcu ac tortor. Mi tempus imperdiet nulla malesuada pellentesque. Parturient montes nascetur ridiculus mus mauris vitae ultricies leo integer. Nulla posuere sollicitudin aliquam ultrices sagittis orci. Orci phasellus egestas tellus rutrum tellus.\n" +
          "\n" +
          "Enim sed faucibus turpis in. Aliquam faucibus purus in massa. Consectetur lorem donec massa sapien faucibus et molestie ac feugiat. Tortor vitae purus faucibus ornare suspendisse sed. Ornare quam viverra orci sagittis eu volutpat. Consectetur purus ut faucibus pulvinar. Condimentum id venenatis a condimentum vitae sapien pellentesque. Donec pretium vulputate sapien nec sagittis aliquam malesuada bibendum. Dui nunc mattis enim ut tellus elementum. Nec feugiat nisl pretium fusce. Dapibus ultrices in iaculis nunc sed. Eget nullam non nisi est sit amet facilisis magna. Suspendisse in est ante in nibh. Gravida dictum fusce ut placerat orci nulla pellentesque. Amet est placerat in egestas erat imperdiet. Adipiscing elit pellentesque habitant morbi tristique senectus et. Ultricies mi eget mauris pharetra et ultrices neque ornare aenean. Facilisis volutpat est velit egestas. Massa sed elementum tempus egestas sed.\n" +
          "\n" +
          "Urna molestie at elementum eu facilisis sed. Mauris sit amet massa vitae. Quam vulputate dignissim suspendisse in est ante in nibh mauris. Magna sit amet purus gravida quis blandit turpis cursus in. Morbi non arcu risus quis. Augue lacus viverra vitae congue eu consequat. Nibh praesent tristique magna sit amet purus gravida quis. Diam sit amet nisl suscipit adipiscing bibendum est. Dignissim diam quis enim lobortis scelerisque fermentum. Donec massa sapien faucibus et molestie ac feugiat sed. Id neque aliquam vestibulum morbi blandit cursus risus at. Vitae tortor condimentum lacinia quis vel. Pellentesque adipiscing commodo elit at imperdiet dui.\n" +
          "\n" +
          "Viverra suspendisse potenti nullam ac tortor vitae purus. Amet porttitor eget dolor morbi non arcu. Felis eget nunc lobortis mattis aliquam faucibus purus in massa. Vestibulum lorem sed risus ultricies tristique. Placerat orci nulla pellentesque dignissim enim sit amet venenatis. Nisi porta lorem mollis aliquam. Sed arcu non odio euismod. Scelerisque eu ultrices vitae auctor. Aliquet enim tortor at auctor urna nunc id. Lacus vestibulum sed arcu non odio. Vel pharetra vel turpis nunc eget lorem. Commodo elit at imperdiet dui accumsan sit amet nulla.\n" +
          "\n" +
          "Odio pellentesque diam volutpat commodo. Lectus nulla at volutpat diam ut venenatis. Aenean euismod elementum nisi quis eleifend quam adipiscing vitae proin. Metus dictum at tempor commodo ullamcorper a lacus. Turpis massa tincidunt dui ut ornare lectus sit amet. Suscipit tellus mauris a diam maecenas. Turpis tincidunt id aliquet risus feugiat. Faucibus turpis in eu mi. Tellus elementum sagittis vitae et leo duis ut diam. Eu mi bibendum neque egestas congue quisque egestas diam in. Ut sem nulla pharetra diam sit. Praesent elementum facilisis leo vel fringilla. Blandit massa enim nec dui nunc mattis enim. Sed enim ut sem viverra aliquet eget.\n" +
          "\n" +
          "Pharetra massa massa ultricies mi quis hendrerit dolor. Nullam ac tortor vitae purus faucibus. Lobortis elementum nibh tellus molestie nunc non. Senectus et netus et malesuada fames. Rhoncus est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat. Ipsum a arcu cursus vitae. Ac feugiat sed lectus vestibulum mattis. Aliquet nec ullamcorper sit amet risus nullam. Egestas fringilla phasellus faucibus scelerisque. Euismod elementum nisi quis eleifend quam adipiscing vitae proin. Scelerisque fermentum dui faucibus in ornare quam viverra orci. Viverra accumsan in nisl nisi scelerisque eu.\n" +
          "\n" +
          "Faucibus turpis in eu mi bibendum. Sed egestas egestas fringilla phasellus faucibus. Lectus mauris ultrices eros in cursus turpis massa. Mauris ultrices eros in cursus turpis massa tincidunt dui. Arcu cursus vitae congue mauris rhoncus aenean. Elementum facilisis leo vel fringilla est ullamcorper. Ut pharetra sit amet aliquam. Pulvinar pellentesque habitant morbi tristique. Risus feugiat in ante metus. Varius morbi enim nunc faucibus a. Sollicitudin ac orci phasellus egestas tellus rutrum tellus pellentesque. Odio ut sem nulla pharetra diam sit amet nisl. Lacinia at quis risus sed vulputate odio ut. Libero nunc consequat interdum varius sit amet mattis. Vel orci porta non pulvinar neque laoreet.\n" +
          "\n" +
          "Ullamcorper morbi tincidunt ornare massa eget egestas purus viverra accumsan. Adipiscing tristique risus nec feugiat. Ac turpis egestas sed tempus urna et. Et malesuada fames ac turpis egestas. Pretium aenean pharetra magna ac placerat vestibulum. Maecenas accumsan lacus vel facilisis volutpat est velit. Pharetra et ultrices neque ornare aenean euismod elementum nisi quis. Volutpat commodo sed egestas egestas fringilla. Pretium quam vulputate dignissim suspendisse in est ante in nibh. Tempus egestas sed sed risus.\n" +
          "\n" +
          "Varius duis at consectetur lorem donec. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper eget. Lectus urna duis convallis convallis tellus id interdum. Iaculis nunc sed augue lacus viverra vitae congue eu consequat. Accumsan lacus vel facilisis volutpat est velit. Sed id semper risus in. Proin fermentum leo vel orci porta non pulvinar. Mi ipsum faucibus vitae aliquet nec ullamcorper sit amet risus. Sed arcu non odio euismod lacinia at quis risus sed. In mollis nunc sed id. Tristique risus nec feugiat in fermentum. Massa placerat duis ultricies lacus sed turpis tincidunt id aliquet. Et sollicitudin ac orci phasellus egestas tellus rutrum tellus. Aliquam ultrices sagittis orci a scelerisque purus semper.\n" +
          "\n" +
          "Porta non pulvinar neque laoreet suspendisse interdum consectetur libero. Pretium nibh ipsum consequat nisl. Habitasse platea dictumst quisque sagittis purus sit amet volutpat consequat. Nunc sed augue lacus viverra vitae congue eu consequat. Dictum non consectetur a erat nam. Turpis egestas maecenas pharetra convallis posuere. Duis convallis convallis tellus id interdum velit laoreet. Lorem sed risus ultricies tristique nulla aliquet enim tortor. Placerat orci nulla pellentesque dignissim enim sit amet venenatis urna. Sagittis vitae et leo duis ut. Vulputate ut pharetra sit amet aliquam id diam. Malesuada pellentesque elit eget gravida cum sociis natoque penatibus. Scelerisque purus semper eget duis at tellus. Ut consequat semper viverra nam. Tincidunt ornare massa eget egestas. Adipiscing elit ut aliquam purus sit amet luctus. Dolor purus non enim praesent elementum. Vitae tempus quam pellentesque nec nam aliquam sem et tortor. Habitasse platea dictumst vestibulum rhoncus. Sem integer vitae justo eget magna.\n" +
          "\n" +
          "Non blandit massa enim nec dui nunc. Vitae aliquet nec ullamcorper sit. Lorem dolor sed viverra ipsum nunc. Amet porttitor eget dolor morbi. Est ullamcorper eget nulla facilisi etiam dignissim diam. Consequat semper viverra nam libero justo laoreet sit amet cursus. Vivamus arcu felis bibendum ut tristique et egestas quis ipsum. Curabitur vitae nunc sed velit dignissim sodales ut. Risus ultricies tristique nulla aliquet enim. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et. Duis at consectetur lorem donec massa sapien faucibus et molestie. Praesent tristique magna sit amet purus gravida quis. Mauris rhoncus aenean vel elit scelerisque. Id aliquet lectus proin nibh nisl condimentum id venenatis. Phasellus egestas tellus rutrum tellus pellentesque eu. Lorem ipsum dolor sit amet consectetur adipiscing elit.\n" +
          "\n" +
          "A cras semper auctor neque. Ornare arcu odio ut sem nulla pharetra diam sit. Pretium nibh ipsum consequat nisl vel. Viverra nam libero justo laoreet sit amet cursus sit. Arcu vitae elementum curabitur vitae nunc sed velit dignissim sodales. Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate. Leo vel orci porta non. Dui vivamus arcu felis bibendum. Nulla facilisi nullam vehicula ipsum a arcu cursus vitae congue. Et molestie ac feugiat sed lectus. Aliquam faucibus purus in massa tempor nec feugiat nisl.\n" +
          "\n" +
          "Vitae et leo duis ut diam quam nulla. Id interdum velit laoreet id donec ultrices tincidunt arcu non. Eget nunc scelerisque viverra mauris in aliquam sem fringilla ut. Sit amet facilisis magna etiam tempor orci. Odio eu feugiat pretium nibh ipsum consequat. Neque aliquam vestibulum morbi blandit cursus risus at ultrices mi. Vestibulum lectus mauris ultrices eros in cursus. Venenatis a condimentum vitae sapien pellentesque habitant morbi tristique. Tristique nulla aliquet enim tortor at auctor urna nunc. Commodo elit at imperdiet dui accumsan. Iaculis urna id volutpat lacus laoreet non curabitur. Quis eleifend quam adipiscing vitae.\n" +
          "\n" +
          "Vitae auctor eu augue ut lectus arcu bibendum. Pharetra convallis posuere morbi leo urna. Vitae justo eget magna fermentum iaculis eu non diam phasellus. Et pharetra pharetra massa massa ultricies. Aliquam vestibulum morbi blandit cursus. Etiam sit amet nisl purus in. Nunc consequat interdum varius sit. Diam sit amet nisl suscipit adipiscing bibendum. Nunc mattis enim ut tellus elementum. Quam lacus suspendisse faucibus interdum posuere lorem ipsum dolor sit. Sed nisi lacus sed viverra. Diam quam nulla porttitor massa id neque aliquam vestibulum. Duis at tellus at urna condimentum mattis pellentesque.\n" +
          "\n" +
          "Tincidunt eget nullam non nisi est sit amet. Ipsum nunc aliquet bibendum enim facilisis gravida neque convallis. Fusce id velit ut tortor. Sit amet purus gravida quis. Urna nec tincidunt praesent semper. Volutpat commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend. Tristique magna sit amet purus gravida quis blandit turpis. Ut sem viverra aliquet eget sit amet tellus cras adipiscing. Blandit libero volutpat sed cras ornare arcu dui vivamus. Ullamcorper a lacus vestibulum sed arcu non odio euismod.\n" +
          "\n" +
          "Leo vel orci porta non. Eu consequat ac felis donec et. Netus et malesuada fames ac turpis egestas sed tempus urna. Eget lorem dolor sed viverra ipsum nunc. Maecenas sed enim ut sem viverra. Vel orci porta non pulvinar neque. At tempor commodo ullamcorper a lacus vestibulum sed arcu. Lobortis elementum nibh tellus molestie nunc non. Pellentesque nec nam aliquam sem et tortor consequat. Interdum varius sit amet mattis vulputate enim nulla aliquet porttitor. Turpis egestas pretium aenean pharetra. Ipsum dolor sit amet consectetur adipiscing elit. Sollicitudin tempor id eu nisl nunc mi. Tellus mauris a diam maecenas sed enim ut sem viverra. Ut morbi tincidunt augue interdum velit euismod in pellentesque massa. Tortor aliquam nulla facilisi cras. Adipiscing tristique risus nec feugiat in fermentum posuere urna. Lacus laoreet non curabitur gravida arcu ac tortor dignissim convallis. Augue mauris augue neque gravida in fermentum et. Commodo viverra maecenas accumsan lacus vel facilisis volutpat est.\n" +
          "\n" +
          "Elit pellentesque habitant morbi tristique. Sollicitudin nibh sit amet commodo nulla. Ipsum faucibus vitae aliquet nec ullamcorper. In nibh mauris cursus mattis molestie a iaculis at erat. Vitae elementum curabitur vitae nunc sed velit. Duis ultricies lacus sed turpis tincidunt. Nibh venenatis cras sed felis eget velit. Tellus at urna condimentum mattis. Enim nunc faucibus a pellentesque sit amet porttitor eget. Sit amet justo donec enim diam. Ac placerat vestibulum lectus mauris ultrices eros in cursus. Sit amet est placerat in egestas erat imperdiet sed. Eget nulla facilisi etiam dignissim diam quis enim lobortis scelerisque. Elit pellentesque habitant morbi tristique senectus et netus. Lectus arcu bibendum at varius vel pharetra. Nam at lectus urna duis convallis convallis. Commodo nulla facilisi nullam vehicula ipsum a. Arcu odio ut sem nulla pharetra diam sit amet nisl. Adipiscing commodo elit at imperdiet dui accumsan sit. In vitae turpis massa sed elementum tempus egestas.\n" +
          "\n" +
          "Quis blandit turpis cursus in hac habitasse platea dictumst quisque. Felis eget velit aliquet sagittis id consectetur. Morbi tristique senectus et netus. Nisi quis eleifend quam adipiscing. Ac orci phasellus egestas tellus rutrum tellus pellentesque. Etiam sit amet nisl purus in mollis. Amet volutpat consequat mauris nunc congue nisi. Nunc aliquet bibendum enim facilisis gravida neque convallis. Scelerisque felis imperdiet proin fermentum leo. Varius quam quisque id diam vel quam elementum pulvinar etiam. Lorem mollis aliquam ut porttitor leo a diam sollicitudin. Ipsum dolor sit amet consectetur adipiscing. Mauris nunc congue nisi vitae suscipit.\n" +
          "\n" +
          "Purus gravida quis blandit turpis cursus in. At in tellus integer feugiat scelerisque. Rhoncus urna neque viverra justo nec ultrices dui. Morbi tristique senectus et netus et malesuada fames ac. At lectus urna duis convallis. Mi bibendum neque egestas congue quisque egestas diam. Volutpat diam ut venenatis tellus in metus vulputate eu scelerisque. Purus semper eget duis at tellus at urna condimentum mattis. Natoque penatibus et magnis dis parturient montes nascetur ridiculus. Nulla facilisi etiam dignissim diam. Elementum sagittis vitae et leo duis ut diam. Faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis. Lobortis elementum nibh tellus molestie. Cras tincidunt lobortis feugiat vivamus at augue eget arcu. Fames ac turpis egestas integer eget aliquet nibh praesent. Sagittis vitae et leo duis ut diam. Viverra mauris in aliquam sem fringilla ut morbi tincidunt augue. Donec ac odio tempor orci dapibus ultrices in iaculis. Faucibus a pellentesque sit amet porttitor. Sem et tortor consequat id porta nibh venenatis cras sed.\n" +
          "\n" +
          "Lorem ipsum dolor sit amet consectetur adipiscing elit pellentesque. Est ante in nibh mauris cursus mattis molestie a iaculis. Et malesuada fames ac turpis egestas sed tempus urna. Sagittis purus sit amet volutpat. Pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus at. Proin fermentum leo vel orci porta non. Aliquam etiam erat velit scelerisque. Convallis a cras semper auctor. Cras fermentum odio eu feugiat pretium nibh ipsum. Lacus sed viverra tellus in hac habitasse. Amet risus nullam eget felis eget nunc lobortis. Magnis dis parturient montes nascetur ridiculus mus mauris. Tortor vitae purus faucibus ornare suspendisse. Justo laoreet sit amet cursus sit amet dictum sit amet. Nam aliquam sem et tortor consequat id porta.\n" +
          "\n" +
          "Vitae proin sagittis nisl rhoncus mattis rhoncus. Tempor nec feugiat nisl pretium fusce. Neque sodales ut etiam sit. Quis vel eros donec ac odio. Habitant morbi tristique senectus et. Metus vulputate eu scelerisque felis. Eget sit amet tellus cras adipiscing enim eu turpis. Euismod in pellentesque massa placerat duis ultricies lacus sed turpis. Sagittis aliquam malesuada bibendum arcu. Sed arcu non odio euismod lacinia at quis. Gravida neque convallis a cras semper auctor neque vitae tempus. Amet justo donec enim diam vulputate ut pharetra. Enim eu turpis egestas pretium aenean pharetra magna ac placerat. In mollis nunc sed id semper. Bibendum ut tristique et egestas quis ipsum suspendisse ultrices gravida. Urna molestie at elementum eu facilisis sed. Amet purus gravida quis blandit turpis cursus in hac habitasse. Viverra mauris in aliquam sem fringilla ut morbi.\n" +
          "\n" +
          "Auctor eu augue ut lectus arcu bibendum at. Diam quam nulla porttitor massa id neque aliquam. Ut consequat semper viverra nam libero justo laoreet sit. Imperdiet proin fermentum leo vel orci porta. Nibh cras pulvinar mattis nunc sed. Neque volutpat ac tincidunt vitae semper. Mauris in aliquam sem fringilla ut morbi. Id leo in vitae turpis massa. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras. Sed elementum tempus egestas sed sed risus. Id consectetur purus ut faucibus. Tincidunt augue interdum velit euismod in pellentesque massa placerat. Quam nulla porttitor massa id. Curabitur vitae nunc sed velit dignissim sodales ut eu sem. Enim ut sem viverra aliquet eget sit amet tellus. Diam quam nulla porttitor massa. Bibendum enim facilisis gravida neque convallis. Molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit sed.\n" +
          "\n" +
          "Lacinia at quis risus sed vulputate odio ut. Volutpat lacus laoreet non curabitur. Donec massa sapien faucibus et molestie ac feugiat sed lectus. At lectus urna duis convallis convallis tellus id. Gravida quis blandit turpis cursus in hac habitasse platea dictumst. Et ligula ullamcorper malesuada proin libero. Nisl condimentum id venenatis a condimentum vitae sapien pellentesque. Placerat in egestas erat imperdiet sed euismod nisi porta lorem. Id ornare arcu odio ut. Tellus mauris a diam maecenas sed enim ut sem. Adipiscing commodo elit at imperdiet dui accumsan sit amet. In iaculis nunc sed augue lacus viverra. Massa tincidunt dui ut ornare lectus sit amet. Sodales ut eu sem integer vitae. Morbi leo urna molestie at elementum eu. Ornare lectus sit amet est placerat in egestas. Non pulvinar neque laoreet suspendisse.\n" +
          "\n" +
          "Malesuada fames ac turpis egestas. Consectetur a erat nam at lectus urna duis convallis convallis. Arcu felis bibendum ut tristique et egestas quis. Fermentum odio eu feugiat pretium nibh ipsum. Duis at consectetur lorem donec massa sapien. Duis ultricies lacus sed turpis tincidunt id aliquet risus feugiat. Id neque aliquam vestibulum morbi blandit cursus risus at. Commodo nulla facilisi nullam vehicula ipsum a. Nunc mattis enim ut tellus elementum. Proin sagittis nisl rhoncus mattis. Enim ut sem viverra aliquet eget sit amet. Sed euismod nisi porta lorem.\n" +
          "\n" +
          "Enim facilisis gravida neque convallis a cras semper auctor neque. Diam sollicitudin tempor id eu nisl. Magna fringilla urna porttitor rhoncus dolor purus non enim praesent. Vitae proin sagittis nisl rhoncus mattis rhoncus urna. Luctus accumsan tortor posuere ac ut consequat semper viverra nam. Ultrices eros in cursus turpis massa tincidunt. Odio pellentesque diam volutpat commodo sed egestas. Augue neque gravida in fermentum et sollicitudin ac. Suscipit adipiscing bibendum est ultricies integer quis. Nunc non blandit massa enim nec dui nunc mattis. Morbi quis commodo odio aenean sed adipiscing diam. Tellus at urna condimentum mattis pellentesque id nibh tortor. At augue eget arcu dictum varius duis at. Varius morbi enim nunc faucibus a pellentesque sit amet porttitor. Nec feugiat in fermentum posuere urna nec. Fames ac turpis egestas maecenas pharetra convallis posuere. Arcu cursus euismod quis viverra nibh cras pulvinar mattis. Quam quisque id diam vel quam elementum pulvinar etiam. Porta non pulvinar neque laoreet suspendisse interdum consectetur libero. Parturient montes nascetur ridiculus mus mauris vitae ultricies.\n" +
          "\n" +
          "Vel facilisis volutpat est velit egestas dui id ornare. Vulputate odio ut enim blandit volutpat. Congue quisque egestas diam in arcu cursus. Convallis aenean et tortor at risus viverra adipiscing. Id consectetur purus ut faucibus pulvinar. Sollicitudin tempor id eu nisl nunc mi ipsum faucibus vitae. Accumsan in nisl nisi scelerisque eu ultrices vitae auctor. Urna molestie at elementum eu facilisis sed. Dui ut ornare lectus sit amet est placerat in. Ullamcorper a lacus vestibulum sed arcu non odio euismod. Vel quam elementum pulvinar etiam non. Adipiscing elit ut aliquam purus sit amet luctus venenatis.\n" +
          "\n" +
          "Tincidunt tortor aliquam nulla facilisi. Aliquet eget sit amet tellus cras adipiscing enim eu. Amet purus gravida quis blandit turpis. Justo eget magna fermentum iaculis. Risus ultricies tristique nulla aliquet enim tortor at auctor urna. Purus ut faucibus pulvinar elementum integer enim neque volutpat. Mauris cursus mattis molestie a iaculis at. Dapibus ultrices in iaculis nunc sed augue. Bibendum ut tristique et egestas quis ipsum suspendisse ultrices. Amet massa vitae tortor condimentum lacinia. Consequat semper viverra nam libero justo laoreet sit amet cursus. Tristique senectus et netus et. Ultrices dui sapien eget mi proin sed libero. Posuere sollicitudin aliquam ultrices sagittis orci a scelerisque. Ante in nibh mauris cursus mattis molestie a iaculis at.\n" +
          "\n" +
          "Quis eleifend quam adipiscing vitae proin sagittis nisl rhoncus. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi. Lobortis feugiat vivamus at augue eget arcu dictum varius. Consequat mauris nunc congue nisi vitae suscipit tellus. Facilisis gravida neque convallis a cras semper auctor neque. Molestie a iaculis at erat. Quis vel eros donec ac. Morbi leo urna molestie at elementum. Morbi tristique senectus et netus et malesuada fames ac turpis. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget. Odio tempor orci dapibus ultrices. Tristique et egestas quis ipsum suspendisse. Massa tempor nec feugiat nisl pretium fusce id velit. Enim nulla aliquet porttitor lacus luctus accumsan tortor. Eu volutpat odio facilisis mauris sit amet massa vitae.\n" +
          "\n" +
          "Ut eu sem integer vitae justo eget magna fermentum. Netus et malesuada fames ac turpis egestas. Volutpat lacus laoreet non curabitur gravida arcu ac. Tincidunt lobortis feugiat vivamus at augue. Vitae turpis massa sed elementum tempus egestas. Lobortis scelerisque fermentum dui faucibus in ornare quam viverra orci. Eu scelerisque felis imperdiet proin fermentum leo vel orci porta. Tempus egestas sed sed risus pretium quam vulputate. Adipiscing tristique risus nec feugiat in. Elementum eu facilisis sed odio morbi quis. Nam libero justo laoreet sit amet cursus sit. Scelerisque in dictum non consectetur a erat nam at lectus. Viverra maecenas accumsan lacus vel. Faucibus et molestie ac feugiat sed lectus vestibulum mattis ullamcorper. Fames ac turpis egestas maecenas.\n" +
          "\n" +
          "Sit amet tellus cras adipiscing enim eu turpis egestas. Quis varius quam quisque id diam vel quam elementum pulvinar. Semper feugiat nibh sed pulvinar proin gravida hendrerit lectus a. Tortor posuere ac ut consequat semper viverra nam libero justo. Egestas fringilla phasellus faucibus scelerisque. Feugiat nibh sed pulvinar proin. Cum sociis natoque penatibus et magnis dis parturient. Arcu felis bibendum ut tristique et egestas quis ipsum. Odio morbi quis commodo odio aenean sed adipiscing diam. At risus viverra adipiscing at in tellus integer. Lacus sed viverra tellus in hac habitasse platea dictumst vestibulum. Dui id ornare arcu odio ut sem nulla pharetra. Elementum pulvinar etiam non quam lacus suspendisse faucibus interdum. At imperdiet dui accumsan sit amet nulla facilisi. Ultricies lacus sed turpis tincidunt. Egestas erat imperdiet sed euismod nisi porta. Accumsan in nisl nisi scelerisque eu ultrices vitae. Pharetra sit amet aliquam id. Iaculis urna id volutpat lacus laoreet.\n" +
          "\n" +
          "Morbi leo urna molestie at elementum. Tellus integer feugiat scelerisque varius morbi. Eu nisl nunc mi ipsum faucibus. Cras semper auctor neque vitae tempus quam pellentesque. Magna fermentum iaculis eu non diam. Mauris ultrices eros in cursus turpis massa tincidunt. Congue nisi vitae suscipit tellus mauris. Nam at lectus urna duis convallis convallis. Quam lacus suspendisse faucibus interdum posuere lorem ipsum. Quis hendrerit dolor magna eget est lorem. Pellentesque adipiscing commodo elit at imperdiet dui. Varius sit amet mattis vulputate enim nulla aliquet porttitor. Ornare arcu odio ut sem nulla pharetra diam sit. Nisi scelerisque eu ultrices vitae. Pharetra pharetra massa massa ultricies mi quis hendrerit. Porta nibh venenatis cras sed felis eget velit. Volutpat consequat mauris nunc congue nisi. Fames ac turpis egestas sed tempus urna.\n" +
          "\n" +
          "Fermentum leo vel orci porta non pulvinar neque laoreet. Faucibus ornare suspendisse sed nisi lacus sed. Turpis massa sed elementum tempus egestas sed. Donec et odio pellentesque diam volutpat commodo sed. Id cursus metus aliquam eleifend mi in. Odio ut enim blandit volutpat maecenas volutpat blandit aliquam. Porttitor massa id neque aliquam vestibulum morbi blandit cursus. Turpis cursus in hac habitasse platea dictumst quisque. Eget nunc scelerisque viverra mauris in aliquam sem fringilla. Nec dui nunc mattis enim ut. Nisi scelerisque eu ultrices vitae auctor eu augue ut lectus. Semper auctor neque vitae tempus quam pellentesque nec nam. Neque ornare aenean euismod elementum nisi quis.\n" +
          "\n" +
          "Nulla facilisi cras fermentum odio eu feugiat. Duis at consectetur lorem donec massa. Praesent semper feugiat nibh sed pulvinar proin. Ullamcorper a lacus vestibulum sed arcu non odio euismod lacinia. Enim diam vulputate ut pharetra sit amet. Nunc faucibus a pellentesque sit amet porttitor eget. Massa ultricies mi quis hendrerit dolor magna eget est. Pulvinar mattis nunc sed blandit libero. Vitae nunc sed velit dignissim sodales. Parturient montes nascetur ridiculus mus mauris vitae ultricies. Eget felis eget nunc lobortis mattis aliquam faucibus purus in. Facilisi nullam vehicula ipsum a arcu cursus. Enim diam vulputate ut pharetra sit amet. Sed risus pretium quam vulputate dignissim suspendisse in. Gravida quis blandit turpis cursus. Mattis pellentesque id nibh tortor.\n" +
          "\n" +
          "Ut pharetra sit amet aliquam id. Dolor sed viverra ipsum nunc aliquet. Purus viverra accumsan in nisl nisi scelerisque eu. Ultrices tincidunt arcu non sodales neque sodales ut. Nunc vel risus commodo viverra maecenas accumsan lacus. Sem et tortor consequat id porta nibh venenatis cras. Fermentum odio eu feugiat pretium nibh ipsum consequat nisl. At tellus at urna condimentum mattis pellentesque id nibh tortor. Pharetra et ultrices neque ornare. Vitae tortor condimentum lacinia quis vel eros donec ac. Ornare suspendisse sed nisi lacus sed viverra tellus. Sagittis id consectetur purus ut faucibus. Volutpat sed cras ornare arcu dui. Erat pellentesque adipiscing commodo elit at imperdiet. Laoreet suspendisse interdum consectetur libero.\n" +
          "\n" +
          "Neque egestas congue quisque egestas. Elit ullamcorper dignissim cras tincidunt lobortis. Nisi scelerisque eu ultrices vitae auctor eu augue. Ut tellus elementum sagittis vitae et leo. Malesuada bibendum arcu vitae elementum curabitur vitae nunc sed. Sollicitudin aliquam ultrices sagittis orci a scelerisque. Senectus et netus et malesuada fames ac turpis egestas integer. Duis ut diam quam nulla porttitor massa. Commodo nulla facilisi nullam vehicula ipsum a arcu cursus. A arcu cursus vitae congue mauris rhoncus aenean. At consectetur lorem donec massa sapien faucibus et molestie ac. Sed blandit libero volutpat sed. Elit scelerisque mauris pellentesque pulvinar. Odio morbi quis commodo odio aenean sed adipiscing diam donec. Cursus in hac habitasse platea dictumst quisque sagittis purus sit. Nam libero justo laoreet sit amet cursus. Mollis nunc sed id semper risus. Pharetra convallis posuere morbi leo urna molestie at elementum.\n" +
          "\n" +
          "Ullamcorper morbi tincidunt ornare massa eget egestas purus. A scelerisque purus semper eget duis at tellus at urna. Velit sed ullamcorper morbi tincidunt. Sagittis nisl rhoncus mattis rhoncus urna neque viverra justo nec. Quam id leo in vitae. Ornare arcu dui vivamus arcu felis bibendum ut tristique et. Lectus proin nibh nisl condimentum id venenatis. Mauris a diam maecenas sed enim ut sem viverra. Feugiat nisl pretium fusce id velit. Vitae turpis massa sed elementum tempus egestas. Diam ut venenatis tellus in metus vulputate. Fermentum posuere urna nec tincidunt. Auctor urna nunc id cursus metus aliquam.\n";
  // endregion
  
  /**
   * Master key used in encryption and decryption mode.
   * 16 bytes = 128 bits.
   */
  private static final byte[] KEY = "00_FELIPE_BONEZI".getBytes(StandardCharsets.UTF_8);
  
  /**
   * Vector salt used in encryption and decryption mode.
   * 16 bytes = 128 bits.
   */
  private static final byte[] SALT = "FELIPEBONEZISALT".getBytes(StandardCharsets.UTF_8);
  
  /**
   * Test with the master key and vector salt has input length divisible by 8.
   */
  @Test
  public void checkKeyAndSaltInputLength() {
    assertEquals(0, KEY.length % 8);
    assertEquals(0, SALT.length % 8);
  }
  
  @Test
  public void whenAESEncryptLongText_thenDecryptSameData() throws CipherException {
    CipherFactory factory   = CipherFactory.getInstance();
    ICipher       cipherAES = factory.get(CipherFactory.Algorithm.AES);
    
    byte[] data          = LARGE_TEXT.getBytes(StandardCharsets.UTF_8);
    byte[] encryptedData = cipherAES.encrypt(KEY, SALT, data);
    assertEquals(0, encryptedData.length % 16);
    
    byte[] decryptedData = cipherAES.decrypt(KEY, SALT, encryptedData);
    Assert.assertArrayEquals(data, decryptedData);
    
    String creditCardNumber = new String(decryptedData);
    assertEquals(LARGE_TEXT, creditCardNumber);
    
    String creditCardNumberStr = cipherAES.decryptToString(KEY, SALT, encryptedData);
    assertEquals(LARGE_TEXT, creditCardNumberStr);
  }
  
}
